/**
 * The two lessons, and the coach marks that walk somebody through them.
 *
 * **A lesson is an ordinary case.** It is generated by the same generator,
 * certified by the same two solvers, stored as the same kind of pack file and
 * proved again by `shipped.test.ts` on every `npm test`. Nothing here is a
 * special mode: what makes it a tutorial is a smaller house — three suspects
 * where Easy has four — and the strip of text below, which watches what the
 * player has actually done and says the next thing to try.
 *
 * **Why the coach marks are a strip and not a spotlight.** The usual shape is
 * a dimmed screen with a hole cut over one button. That needs every step to
 * name a live DOM node, which ties the lesson to the markup of four
 * components and breaks silently the first time one of them is rearranged —
 * and it is the kind of break nothing here can test, because the UI is not
 * tested (see CLAUDE.md). A strip that reads the *game state* instead cannot
 * point at the wrong button, because it points at nothing: it says what to
 * do, and it notices when it has been done. The cost is that it teaches by
 * telling rather than by pointing, which for five steps is a fair trade.
 *
 * **Steps never block.** A step is retired when its condition holds, and
 * conditions are written so that a player who does something else useful
 * moves on anyway — the one that suggests a hint retires on collecting a few
 * more cards instead. A tutorial that will not proceed until you press the
 * button it wants is worse than no tutorial.
 */

/** The pack directory the lessons live in. */
export const TUTORIAL_PACK = "tutorial";

/** What the strip can see. Everything is already in `Game`. */
export interface CoachState {
  /** Rooms examined so far. */
  examined: number;
  /** Questions put, by the picker or in words. */
  asked: number;
  /** Cards collected. */
  cards: number;
  /** Cells the player has pencilled or crossed. */
  marked: number;
  hints: number;
  wrong: number;
  solved: boolean;
}

export interface CoachStep {
  /** Stable, so a step can be identified in a test without its prose. */
  id: string;
  text: string;
  /** True once the player has done it, or done something better. */
  done(s: CoachState): boolean;
}

export interface Lesson {
  /** The case id, which is also the pack file's name. */
  id: string;
  /** 1 or 2: the order they are meant to be taken in. */
  n: number;
  name: string;
  /** One line on the home screen. */
  blurb: string;
  steps: readonly CoachStep[];
  /** Shown on the summary when the lesson is finished. */
  outro: string;
}

/**
 * Lesson one: the loop.
 *
 * Examine, ask, pencil, deduce, accuse — in that order, because that is the
 * order the game rewards. The case is `SK1-E-tut1`: three suspects, four
 * rooms, four hours, nobody lying, and two actions between the player and
 * every card the proof needs.
 */
const ONE: Lesson = {
  id: "SK1-E-tut1",
  n: 1,
  name: "Lesson one — the loop",
  blurb: "Three suspects, four rooms, four hours, and nobody lying to you.",
  outro:
    "That is the whole game. Everything else is a bigger house and more to keep straight.",
  steps: [
    {
      id: "examine",
      text:
        "Everything you learn arrives as an evidence card, and examining a " +
        "room is the cheapest way to get one. Open the map and examine a room " +
        "— the Taproom, where he was found, is a fair place to start.",
      done: (s) => s.examined >= 1,
    },
    {
      id: "ask",
      text:
        "Now ask somebody. Pick a suspect and a topic — an hour, a room, or " +
        "another person — and they will tell you what they saw. Roughly half " +
        "of all questions turn something up.",
      done: (s) => s.asked >= 1,
    },
    {
      id: "mark",
      text:
        "The notebook is where you do the thinking. Click a cell to cross a " +
        "room out for that person and that hour. Cross out enough and only " +
        "one room is left, which is how a row gets solved.",
      done: (s) => s.marked >= 1,
    },
    {
      id: "hint",
      text:
        "Stuck? Press H. A hint never just tells you the answer — it gives " +
        "you the next deduction your cards already support, and says which " +
        "rule it used. Press C and the game will say, in one bit, whether " +
        "everything you have written down is right.",
      done: (s) => s.hints >= 1 || s.cards >= 5,
    },
    {
      id: "accuse",
      text:
        "When you know who and when, press A and name them. You accuse a " +
        "person and an hour — the room is already known, because that is " +
        "where the body is.",
      done: (s) => s.solved,
    },
  ],
};

/**
 * Lesson two: the lie.
 *
 * `SK1-H-tut2` is the same size with one more hour, and the culprit's
 * testimony may be false. Its proof runs: the window narrows, Nora is cleared
 * by opportunity, Ida's own statements turn out to be impossible — so Ida is
 * the killer and Walter is therefore innocent — and *then* Walter's card,
 * worthless while he might have been lying, fixes the hour.
 *
 * That last move is what the plan asked this lesson to teach and called
 * "clearing someone to trust them". It is worth knowing that it is not a rule
 * you can point at: the solver's only two tier-3 rules are
 * `self-incrimination` and `conflict-pair`, and trust is the mechanism
 * underneath them (`solver/state.ts#trustedMask`). So the lesson teaches it
 * the way the case does — as the payoff of the step before it.
 */
const TWO: Lesson = {
  id: "SK1-H-tut2",
  n: 2,
  name: "Lesson two — the lie",
  blurb: "The same size of house, and this time the killer lies to you.",
  outro:
    "From here on, every Hard and Expert case has a liar in it. The method " +
    "never changes: find the story that cannot be true.",
  steps: [
    {
      id: "read",
      text:
        "One rule changes: the killer's statements may be false. Everyone " +
        "else still tells you the truth — they simply do not tell you " +
        "everything. Silence proves nothing.",
      done: (s) => s.examined + s.asked >= 1,
    },
    {
      id: "gather",
      text:
        "Physical evidence never lies, so examining rooms is solid ground. " +
        "The case file has already given you three facts: a door locked until " +
        "eight, a room Nora Blyth was never let into, and how many it holds.",
      done: (s) => s.examined + s.asked >= 3,
    },
    {
      id: "contradiction",
      text:
        "Now collect statements — including ones you cannot trust yet. A " +
        "statement that cannot possibly be true convicts the person who made " +
        "it, because the innocent never lie. That is a card working for you " +
        "even when it is false.",
      done: (s) => s.asked >= 3 || s.cards >= 6,
    },
    {
      id: "trust",
      text:
        "And it cuts the other way. The moment somebody is proved innocent, " +
        "everything they said becomes solid ground — so clearing a suspect is " +
        "worth as much as suspecting one. Press H if the chain is hard to see.",
      done: (s) => s.marked >= 1 || s.hints >= 1,
    },
    {
      id: "accuse",
      text: "Name your killer and the hour.",
      done: (s) => s.solved,
    },
  ],
};

/** In the order they are meant to be taken. */
export const LESSONS: readonly Lesson[] = [ONE, TWO];

export function lessonFor(caseId: string): Lesson | null {
  return LESSONS.find((l) => l.id === caseId) ?? null;
}

/**
 * The step to show, or null when the lesson is done.
 *
 * The first step whose condition does not yet hold. Deliberately not "the
 * next one after the last one completed": a player who accuses on their third
 * card has finished the lesson whatever the earlier steps say, and a player
 * who undoes all their marks should be told about the notebook again.
 */
export function coachStep(lesson: Lesson, state: CoachState): CoachStep | null {
  return lesson.steps.find((step) => !step.done(state)) ?? null;
}

/** How far along, for the strip's "2 of 5". */
export function coachProgress(
  lesson: Lesson,
  state: CoachState,
): { at: number; of: number } {
  const of = lesson.steps.length;
  const step = coachStep(lesson, state);
  // A finished lesson is "5 of 5", not "6 of 5". The strip does not render at
  // all once `coachStep` returns null, so this only shows up in a caller that
  // asks for the count on its own — which is why it is a test rather than
  // something anybody would have noticed.
  return { at: step === null ? of : lesson.steps.indexOf(step) + 1, of };
}
